pom/pom.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/4)
=> Changes in pom

template/Widget.template, template/helpers.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/7)
=> Fix adding widget.event.* to imports when there are no events generated

gulpfile.js, package.json, pom-template.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/9)
=> Renamed the pom template file and artifact id

gulpfile.js, lib/com/vaadin/components/gwt/polymer/client/Polymer.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/6)
=> Remove the ImportsMap.java

gulpfile.js, package.json, template/helpers.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/8)
=> Parsing markdown descriptions so as they are wellformed in jdoc

lib/com/vaadin/components/gwt/polymer/client/Polymer.java, lib/com/vaadin/components/gwt/polymer/client/PolymerWidget.java, template/Widget.template
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/11)
=> Adding overloaded methods to specify component url

lib/com/vaadin/components/gwt/polymer/client/Polymer.java, lib/com/vaadin/components/gwt/polymer/client/webapi/Function.java, template/Widget.template
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/metathesis/12)
=> Add callbacks to imports.

gulpfile.js, template/helpers.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/16)
=> Parse nested behaviors recursively.

gulpfile.js, template/helpers.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/17)
=> Export nested behavior events.

lib/com/vaadin/polymer/Polymer.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/21)
=> More accurate ready check. Change dynamic import API

template/tasks/global-variables.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/19)
=> Correct default artifactId

template/helpers.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/20)
=> Make generator always generate getters with prefix `get`

lib/com/vaadin/polymer/elemental/Element.java, template/tasks/pre-analyze.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/22)
=> Adding another missing event used in examples

lib/com/vaadin/polymer/Polymer.java, lib/com/vaadin/polymer/PolymerWidget.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/23)
=> Ability to load multiple tags/hrefs reusing a unique callback

template/pom.template
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/24)
=> Set source encoding to avoid compile errors on Windows

lib/com/vaadin/polymer/Polymer.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/25)
=> Fix FF, Safari and IE lazy loading

template/Element.template, template/Widget.template, template/helpers.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/26)
=> Handle attributes with overloaded setters

template/pom.template
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/28)
=> Update version to 1.0.2.0-alpha1

lib/com/vaadin/polymer/PolymerWidget.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/29)
=> Remove legacy (for version 0.5) common setters from PolymerWidget

template/Widget.template
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/30)
=> Remove unnecessary accompanying setters for boolean properties

lib/com/vaadin/polymer/PolymerWidget.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/34)
=> Prevent wrong imports based on tag name (e.g paper-tab/paper-tab.html)

lib/com/vaadin/polymer/Polymer.java, lib/com/vaadin/polymer/PolymerWidget.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/35)
=> Adding ready functions to Polymer helper classes

lib/com/vaadin/polymer/elemental/Element.java, lib/com/vaadin/polymer/elemental/Node.java, lib/com/vaadin/polymer/elemental/NodeList.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/38)
=> Add few methods to web API

lib/com/vaadin/polymer/PolymerWidget.java, template/Widget.template
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/41)
=> Alert the user if JsInterop was not enabled

README.md, gulpfile.js, package.json
See #43
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/45)
=> Read bower configuration from .bowerrc.

lib/com/vaadin/polymer/Polymer.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/gwt-api-generator/48)
=> Use more reliable way to detect when components are ready

template/pom.template
Update to latest elemental2 version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/manolo/gwt-api-generator/88)
=> update elemental version to 1.0.0-RC1
